sudo: required
services:
  - docker

before_install:
  - docker build -t ebun/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ebun/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-583951189311"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  
  
